name: Release
on:
  - push
  - pull_request
  - workflow_dispatch

permissions:
  contents: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: latest

      - name: Release
        run : |
          pnpm --package=@semantic-release/commit-analyzer \
          --package=@semantic-release/git \
          --package=@semantic-release/exec \
          --package=semantic-release@19 \
          dlx semantic-release

      - name: Create GitHub Release
        if: (github.ref == 'refs/heads/main') && (!contains(github.event.head_commit.message, 'chore:'))
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          body: Release ${{ env.RELEASE_VERSION }}
