name: RPM Build

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up RPM build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build composer binary with cargo
        run: |
          cargo build --release
      - name: Prepare RPM spec file
        run: |
          export APP_NAME="composer"
          export APP_VERSION=$(git describe --tags --abbrev=0)
          export APP_SUMMARY="A docker-compose package manager."
          export APP_LICENSE="MIT"
          export APP_URL="https://github.com/ByteSquid/composer-rust"
          export APP_SOURCE_URL="target/release/composer"
          export APP_DESCRIPTION="A docker-compose package manager."
          export APP_AUTHOR="Sam Ruff"
          export APP_AUTHOR_EMAIL="sam@bytesquid.com"
          mkdir -p $HOME/rpmbuild/{SPECS,SOURCES}
          envsubst < composer.spec.template > $HOME/rpmbuild/SPECS/composer.spec
          cp target/release/composer $HOME/rpmbuild/SOURCES/
      - name: Build RPM
        run: rpmbuild -ba $HOME/rpmbuild/SPECS/composer.spec
      - name: Upload RPM artifact
        uses: actions/upload-artifact@v2
        with:
          name: composer_rpm
          path: $HOME/rpmbuild/RPMS/**/*.rpm
